# Generated by Django 6.0.6 on 2026-07-06 06:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_meeting_intervention_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project', max_length=250)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(help_text='Project deadline date')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(blank=True, help_text='Thematic domain this project belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='tracker.domain')),
                ('lead_employee', models.ForeignKey(blank=True, help_text='Employee leading this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='tracker.employee')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['deadline', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task description / title', max_length=250)),
                ('due_date', models.DateField(help_text='Task due date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('hours_logged', models.DecimalField(decimal_places=2, default=0.0, help_text='Hours logged on this task', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Employee assigned to this task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.employee')),
                ('project', models.ForeignKey(help_text='Project this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tracker.project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_date', 'title'],
            },
        ),
    ]
