# Generated by Django 6.0.6 on 2026-07-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_employee_role_employee_supervisor_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder'), ('hr', 'HR'), ('supervisor', 'Supervisor'), ('employee', 'Employee'), ('intern', 'Intern'), ('volunteer', 'Volunteer')], default='employee', help_text='Role-Based Access Control level', max_length=20),
        ),
    ]
