# Generated by Django 6.0.6 on 2026-07-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(help_text='Employees assigned to this task', related_name='tasks', to='tracker.employee'),
        ),
    ]
