# Generated by Django 6.0.6 on 2026-07-07 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeStats',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='tracker.employee')),
                ('total_assigned', models.PositiveIntegerField(default=0)),
                ('total_completed', models.PositiveIntegerField(default=0)),
                ('total_pending', models.PositiveIntegerField(default=0)),
                ('total_awaiting', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_recalculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Stats',
                'verbose_name_plural': 'Employee Stats',
            },
        ),
        migrations.CreateModel(
            name='TaskChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short descriptive title of the checklist item', max_length=250)),
                ('description', models.TextField(blank=True, help_text='Detailed description or acceptance criteria')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_VERIFICATION', 'Awaiting Verification'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=30)),
                ('rejection_feedback', models.TextField(blank=True, help_text='Feedback provided by the supervisor when rejecting a submission')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the employee marked this item as done', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the supervisor approved or rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Employee this checklist item is assigned to', on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tracker.employee')),
                ('created_by', models.ForeignKey(help_text='Supervisor / founder who created this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklist_items', to='tracker.employee')),
            ],
            options={
                'verbose_name': 'Task Checklist Item',
                'verbose_name_plural': 'Task Checklist Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_to', 'status'], name='tracker_chk_assignee_stat_idx'), models.Index(fields=['status', 'created_at'], name='tracker_chk_status_date_idx')],
            },
        ),
    ]
