# Generated by Django 6.0.6 on 2026-07-08 09:57

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_employeestats_taskchecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(default='Enterprise ERP', help_text='The dynamic name of the enterprise', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Upload the enterprise logo', null=True, upload_to='organization/logos/', validators=[tracker.models.validate_image_file])),
                ('is_setup_complete', models.BooleanField(default=False, help_text='Indicates if the initial onboarding setup is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Profile',
                'verbose_name_plural': 'Organization Profiles',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/photos/', validators=[tracker.models.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload meeting agenda, minutes document, or presentation', null=True, upload_to='meetings/attachments/', validators=[tracker.models.validate_document_file]),
        ),
    ]
