# Generated by Django 6.0.6 on 2026-07-08 15:17

import django.db.models.deletion
import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_organizationprofile_alter_employee_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the enterprise', max_length=255)),
                ('subdomain', models.CharField(help_text='Unique subdomain for routing (e.g. "cysd")', max_length=63, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Upload the enterprise logo', null=True, upload_to='organization/logos/', validators=[tracker.models.validate_image_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enterprise',
                'verbose_name_plural': 'Enterprises',
            },
        ),
        migrations.DeleteModel(
            name='OrganizationProfile',
        ),
        migrations.AddField(
            model_name='domain',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tracker.enterprise'),
        ),
        migrations.AddField(
            model_name='employee',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tracker.enterprise'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tracker.enterprise'),
        ),
        migrations.AddField(
            model_name='project',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tracker.enterprise'),
        ),
        migrations.AddField(
            model_name='task',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tracker.enterprise'),
        ),
        migrations.AddField(
            model_name='taskchecklist',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tracker.enterprise'),
        ),
    ]
