# Generated by Django 6.0.6 on 2026-07-08 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20260708_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tracker.enterprise'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tracker.enterprise'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tracker.enterprise'),
        ),
        migrations.AlterField(
            model_name='project',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tracker.enterprise'),
        ),
        migrations.AlterField(
            model_name='task',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tracker.enterprise'),
        ),
        migrations.AlterField(
            model_name='taskchecklist',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tracker.enterprise'),
        ),
    ]
