# Generated by Django 4.2.30 on 2026-07-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_domain_enterprise_alter_employee_enterprise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermission',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='permissions', serialize=False, to='tracker.employee')),
                ('can_manage_employees', models.BooleanField(default=False, help_text='Can create / edit / deactivate employee records')),
                ('can_manage_organization', models.BooleanField(default=False, help_text='Can edit enterprise / organisation settings')),
                ('can_view_advanced_analytics', models.BooleanField(default=False, help_text='Can access the employee-performance analytics page')),
                ('can_assign_checklist_items', models.BooleanField(default=False, help_text='Can create TaskChecklist items and assign them to employees')),
                ('can_approve_checklist_items', models.BooleanField(default=False, help_text='Can approve / reject submitted TaskChecklist items')),
                ('can_read_confidential_meetings', models.BooleanField(default=False, help_text='Can view full meeting agenda, minutes, and action points (when False, these fields are masked)')),
                ('can_log_hours', models.BooleanField(default=False, help_text='Can log hours on tasks assigned to them')),
                ('can_access_admin_panel', models.BooleanField(default=False, help_text='Grants is_staff + tracker app permissions on the linked User')),
                ('checklist_assign_scope', models.CharField(choices=[('none', 'None'), ('own_team', 'Own Team'), ('all', 'All')], default='none', help_text="'none' = cannot assign, 'own_team' = direct reports only, 'all' = any employee in the enterprise", max_length=10)),
                ('checklist_approve_scope', models.CharField(choices=[('none', 'None'), ('own_team', 'Own Team'), ('all', 'All')], default='none', help_text="'none' = cannot approve, 'own_team' = direct reports only, 'all' = any employee in the enterprise", max_length=10)),
                ('analytics_scope', models.CharField(choices=[('none', 'None'), ('own_team', 'Own Team'), ('all', 'All')], default='none', help_text="'none' = own data only, 'own_team' = own direct reports, 'all' = entire enterprise", max_length=10)),
            ],
            options={
                'verbose_name': 'Employee Permission',
                'verbose_name_plural': 'Employee Permissions',
            },
        ),
    ]
