# Generated by Django 4.2.30 on 2026-07-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_role_and_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role_tag',
        ),
        migrations.RemoveField(
            model_name='employeepermission',
            name='can_manage_roles',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
