# Generated by Django 4.2.30 on 2026-07-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_remove_employee_role_remove_employee_role_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='code',
            field=models.CharField(db_index=True, help_text='Short identifier code (e.g. "EDU", "HLT")', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, help_text='Unique employee / volunteer ID (e.g. "CYSD-2024-001")', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='subdomain',
            field=models.CharField(db_index=True, help_text='Unique subdomain for routing (e.g. "cysd")', max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(db_index=True, help_text='Date of the meeting'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20),
        ),
    ]
