# Generated by Django 4.2.30 on 2026-07-30 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_domain_code_alter_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='project',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='task',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='taskchecklist',
            name='enterprise',
        ),
        migrations.DeleteModel(
            name='Enterprise',
        ),
    ]
