# Generated by Django 4.2.30 on 2026-08-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_taskchecklist_is_self_allocated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepermission',
            name='analytics_scope',
        ),
        migrations.RemoveField(
            model_name='employeepermission',
            name='can_log_hours',
        ),
        migrations.RemoveField(
            model_name='employeepermission',
            name='can_view_advanced_analytics',
        ),
        migrations.RemoveField(
            model_name='task',
            name='hours_logged',
        ),
    ]
