# Generated by Django 4.2.30 on 2026-08-03 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_remove_employeepermission_analytics_scope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='Employee who called/organized this meeting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to='tracker.employee'),
        ),
    ]
