# Generated by Django 4.2.30 on 2026-08-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_meeting_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='can_self_assign_tasks',
            field=models.BooleanField(default=False, help_text='Can create self-allocated checklist tasks (employee picks up work proactively)'),
        ),
    ]
