# Generated by Django 4.2.30 on 2026-08-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_add_can_self_assign_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='can_view_employee_analytics',
            field=models.BooleanField(default=False, help_text='Can view team / organization employee workload analytics'),
        ),
        migrations.AddField(
            model_name='employeepermission',
            name='employee_analytics_scope',
            field=models.CharField(choices=[('none', 'None'), ('own_team', 'Own Team'), ('all', 'All')], default='none', help_text="'none' = cannot view, 'own_team' = direct reports only, 'all' = any employee in the enterprise", max_length=10),
        ),
    ]
