# Generated by Django 4.2.30 on 2026-08-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_add_employee_analytics_permissions'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='tracker_emp_domain_i_idx',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='domain',
        ),
        migrations.AddField(
            model_name='employee',
            name='domains',
            field=models.ManyToManyField(blank=True, help_text='Programme domains the employee works in', related_name='employees', to='tracker.domain'),
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Projects this employee is enrolled in', related_name='enrolled_employees', to='tracker.project'),
        ),
        migrations.AlterField(
            model_name='employeepermission',
            name='checklist_approve_scope',
            field=models.CharField(choices=[('none', 'None'), ('own_team', 'Own Team'), ('own_domain', 'Own Domains'), ('own_project', 'Own Projects'), ('all', 'All')], default='none', help_text="'none' = cannot approve, 'own_team' = direct reports only, 'own_domain' = same domains, 'own_project' = same projects, 'all' = any employee", max_length=15),
        ),
        migrations.AlterField(
            model_name='employeepermission',
            name='checklist_assign_scope',
            field=models.CharField(choices=[('none', 'None'), ('own_team', 'Own Team'), ('own_domain', 'Own Domains'), ('own_project', 'Own Projects'), ('all', 'All')], default='none', help_text="'none' = cannot assign, 'own_team' = direct reports only, 'own_domain' = same domains, 'own_project' = same projects, 'all' = any employee", max_length=15),
        ),
        migrations.AlterField(
            model_name='employeepermission',
            name='employee_analytics_scope',
            field=models.CharField(choices=[('none', 'None'), ('own_team', 'Own Team'), ('own_domain', 'Own Domains'), ('own_project', 'Own Projects'), ('all', 'All')], default='none', help_text="'none' = cannot view, 'own_team' = direct reports only, 'own_domain' = same domains, 'own_project' = same projects, 'all' = any employee", max_length=15),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['employee_id'], name='tracker_emp_id_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='tracker_emp_active_idx'),
        ),
    ]
