# Generated by Django 4.2.30 on 2026-08-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_remove_employee_tracker_emp_domain_i_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='convenor',
            field=models.ForeignKey(blank=True, help_text='Employee designated as the Meeting Convenor (responsible for calling and coordinating the meeting)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convened_meetings', to='tracker.employee'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='facilitator',
            field=models.ForeignKey(blank=True, help_text='Employee designated as the Meeting Facilitator (responsible for guiding discussions and maintaining flow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitated_meetings', to='tracker.employee'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='rapporteur',
            field=models.ForeignKey(blank=True, help_text='Employee designated as the Meeting Rapporteur (responsible for documenting proceedings and preparing reports)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapporteur_meetings', to='tracker.employee'),
        ),
    ]
