# Generated by Django 4.2.30 on 2026-08-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_add_meeting_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepermission',
            name='can_schedule_meetings',
            field=models.BooleanField(default=False, help_text='Can schedule new meetings via the frontend'),
        ),
    ]
