# Generated by Django 4.2.30 on 2026-08-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_update_meeting_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('smt', 'SMT Meeting'), ('leadership', 'Leadership Meeting'), ('zonal_integration', 'Zonal Integration Meeting'), ('block_integration', 'Block Integration Meeting'), ('board', 'Board Meeting'), ('agm', 'AGM Meeting'), ('program_division', 'Program Division Meeting'), ('psd', 'PSD Meeting')], default='smt', max_length=20),
        ),
    ]
